title: Computer Science A
description: We will use this to collaborate on projects.
template:
  repo: computer-science-a-template
  name: computer-science-a
  description: All projects can be found here.
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: Project 1
    description: Hello World
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
